# network_layer/topology.py

from physical_layer.fiber_channel import FiberLink
from physical_layer.fso_channel import FSOLink

class HybridQKDNetwork:
    """
    Mixed fiber + FSO trusted relay network.
    Manages per-link physical state and
    exposes a uniform interface to the routing layer.
    """

    def __init__(self, config):
        self.nodes = config.nodes
        self.links = self._build_links(config.link_configs)
        self.key_pools = {
            (i,j): config.initial_key_pool
            for (i,j) in self.links
        }

    def _build_links(self, link_configs):
        links = {}
        for cfg in link_configs:
            i, j = cfg['nodes']
            if cfg['type'] == 'fiber':
                links[(i,j)] = FiberLink(i, j, cfg['length_km'], **cfg['params'])
            elif cfg['type'] == 'fso':
                links[(i,j)] = FSOLink(i, j, cfg['length_km'], **cfg['params'])
        return links

    def get_network_state(self, time: float) -> dict:
        """
        Sample all link states at current time.
        Returns unified state dict regardless of link type.
        This is what the RL environment observes.
        """
        states = {}
        for (i,j), link in self.links.items():
            conditions = link.sample_conditions(time)
            states[(i,j)] = link.get_rl_state(
                conditions,
                self.key_pools[(i,j)]
            )
            states[(i,j)]['conditions'] = conditions
            states[(i,j)]['link_type_str'] = link.link_type()
        return states

    def update_key_pools(self, time: float, dt: float,
                         traffic: dict):
        """
        Update all key pools:
        - Add keys generated by SKR during dt
        - Subtract keys consumed by routed traffic
        """
        for (i,j), link in self.links.items():
            conditions = link.sample_conditions(time)
            SKR = link.SKR_finite(conditions)

            # Key generation
            new_keys = SKR * dt
            self.key_pools[(i,j)] = min(
                self.key_pools[(i,j)] + new_keys,
                link.n_block   # pool capacity
            )

            # Key consumption from routing
            consumed = traffic.get((i,j), 0)
            self.key_pools[(i,j)] = max(
                0,
                self.key_pools[(i,j)] - consumed
            )

    def get_link_type_mask(self):
        """
        Returns which links are FSO vs fiber.
        Useful for the RL agent to learn
        type-specific routing policies.
        """
        return {
            (i,j): link.link_type()
            for (i,j), link in self.links.items()
        }
